language: perl

# remember need at least one install command, even if there are no
# prereqs, else travis will try to install deps using cpanm
# which is not what we want since this is a Dist::Zilla dist.
install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing   | cpanm -n
  - cpanm -n Pod::Find Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true

perl:
  - "5.20"
  - "5.20-shrplib"

script:
  - dzil test -v

sudo: false
